---
title: "Brian Kwiecinski's Digital Resume"
date: 2019-01-20
---
author: Brian Kwiecinski
email: 46533363+briankwie@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  My name is __Brian Kwiecinski__ and this is my __GitHub Resume__.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
